---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-external-secrets
  namespace: arr-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: seerr-database
  dataFrom:
    - extract:
        key: apps/seerr/database
        # property: .
