apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-wekan
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  template:
    metadata:
      name: '{{ .name }}-wekan'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: wekan

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: clusters/{{.name}}/extras/wekan
          ref: values

        - repoURL: https://wekan.github.io/charts
          chart: wekan
          targetRevision: 8.52.0
          helm:
            releaseName: wekan
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{.name}}/values/wekan.yaml

      syncPolicy:
        automated:
          prune: false
        syncOptions:
        - CreateNamespace=true
