apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-netbox
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - management
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: '{{ .name }}-netbox'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: netbox

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: cluster/hub/extras/netbox
          ref: values

        - repoURL: https://charts.hknlab.io
          chart: netbox
          targetRevision: 0.1.1
          helm:
            releaseName: netbox
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/hub/values/netbox.yaml

      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true

      ignoreDifferences:
        - group: Batch
          kind: Job
