apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-home-assistant-matter-server
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: management
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: '{{ .name }}-home-assistant-matter-server'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: home-assistant

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: cluster/{{ .name }}/extras/home-assistant-matter-server
          ref: values

        - repoURL: https://charts.derwitt.dev
          chart: home-assistant-matter-server
          targetRevision: 3.1.1  # For Helm, this refers to the chart version.
          helm:
            releaseName: matter-server
            values: |
              fullnameOverride: matter-server
              nameOverride: matter-server

            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{ .name }}/values/home-assistant-matter-server.yaml

      syncPolicy:
        managedNamespaceMetadata:
          annotations:
            k8s.ovn.org/multicast-enabled: 'true'
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
