---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zammad-postgresql-external-secrets
  namespace: zammad
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: zammad-postgresql
  dataFrom:
    - extract:
        key: apps/zammad/postgresql
        # property: .
