apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: configarr-external-secrets
  namespace: arr-management
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: configarr-secrets
  data:
    - secretKey: secrets.yml
      remoteRef:
        key: apps/configarr
        property: secrets.yml
    - secretKey: config.yml
      remoteRef:
        key: apps/configarr
        property: config.yml
