apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: 'https://api.prod.openshift.hkn.lab:6443'
  sourceRepos:
    - '*'
status: {}
