apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-cloudflare-tunnel
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  template:
    metadata:
      name: '{{ .name }}-cloudflare-tunnel'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: cloudflare-tunnel-ingress-controller

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: cluster/{{ .name }}/extras/cloudflare-tunnel-ingress-controller
          ref: values

        - repoURL: https://helm.strrl.dev
          chart: cloudflare-tunnel-ingress-controller
          targetRevision: 0.0.18
          helm:
            releaseName: cloudflare-tunnel-ingress-controller
            ignoreMissingValueFiles: true
            valueFiles:
              # - $values/environment/{{ .metadata.labels.environment }}/values/cloudflare-tunnel-ingress-controller.yaml
              - $values/cluster/{{ .name }}/values/cloudflare-tunnel-ingress-controller.yaml

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
