kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm-wizarr-scc
  namespace: arr-management
subjects:
  - kind: ServiceAccount
    name: default
    namespace: arr-management
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
