apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-hashicorp-vault
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: management
        values:
          env: '{{index .metadata.labels "environment"}}'
          cluster: '{{ .name }}'
  template:
    metadata:
      name: '{{ .name }}-hashicorp-vault'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: vault

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: cluster/hub/extras/hashicorp-vault
          ref: values

        - repoURL: https://helm.releases.hashicorp.com
          chart: vault  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
          targetRevision: 0.31.0  # For Helm, this refers to the chart version.
          helm:
            releaseName: vault
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/environment/{{ .values.env }}/values/hashicorp-vault.yaml
              - $values/cluster/{{ .values.cluster }}/values/hashicorp-vault.yaml

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true

      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: MutatingWebhookConfiguration
          name: vault-agent-injector-cfg
          jqPathExpressions:
          - .webhooks[]? | .clientConfig.caBundle
