apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-hcp-pullsecret-prod
  namespace: clusters
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: pullsecret-cluster-prod
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - extract:
        key: cluster/prod/install/pull-secret
