---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-hcp-oauth-certs-prod
  namespace: clusters
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: oauth-certs-prod
  data:
    - secretKey: tls.crt
      remoteRef:
        key: cluster/prod/certs/oauth
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: cluster/prod/certs/oauth
        property: tls.key
