kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm-wekan-mongodb-scc
  namespace: wekan
subjects:
  - kind: ServiceAccount
    name: default
    namespace: wekan
  - kind: ServiceAccount
    name: wekan
    namespace: wekan
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
