apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-rhbk
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  template:
    metadata:
      name: '{{ .name }}-rhbk'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: keycloak

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: clusters/{{ .name }}/extras/rhbk
          ref: values

        - repoURL: https://charts.hknlab.io
          chart: rhbk
          targetRevision: 0.1.0
          helm:
            releaseName: keycloak
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/clusters/{{ .name }}/values/rhbk.yaml

      syncPolicy:
        automated:
          prune: false
        syncOptions:
          - CreateNamespace=true
