apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-rhacm-gitops-project
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        values:
          env: '{{ index .metadata.labels "environment" }}'
        # selector:
        #   matchExpressions:
        #     - key: vendor
        #       operator: In
        #       values:
        #         - Openshift
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ .name }}-rhacm-gitops-project'
    spec:
      project: gitops

      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops

      sources:
        - repoURL: https://charts.hknlab.io
          chart: rhacm-gitops-project
          targetRevision: 0.1.1
          helm:
            releaseName: '{{ .name }}'
            valuesObject:
              clusterName: '{{ .name }}'
              clusterApiServer: '{{ .server }}'

      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
