apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: spoke-argocd-crd
  namespace: open-cluster-management-policies
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/description: Ensure the gitops operator has an argocd instance
    policy.open-cluster-management.io/standards: ""
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: spoke-policy-argocd
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1beta1
                kind: ArgoCD
                metadata:
                  name: openshift-gitops
                  namespace: openshift-gitops
                spec:
                  applicationSet:
                    resources:
                      requests:
                        cpu: 250m
                        memory: 512Mi
                      limits:
                        cpu: "2"
                        memory: 1Gi
                  rbac:
                    defaultPolicy: ""
                    scopes: "[groups]"
                  server:
                    resources:
                      requests:
                        cpu: 125m
                        memory: 128Mi
                      limits:
                        cpu: 500m
                        memory: 256Mi
                  sso:
                    dex:
                      resources:
                        requests:
                          cpu: 250m
                          memory: 128Mi
                        limits:
                          cpu: 500m
                          memory: 256Mi
                      openShiftOauth: true
                    provider: dex
          remediationAction: inform
          severity: critical
  remediationAction: inform
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: spoke-argocd-crd-placement
  namespace: open-cluster-management-policies
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: NotIn
              values:
                - local-cluster
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: spoke-argocd-crd-placement-binding
  namespace: open-cluster-management-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: spoke-argocd-crd-placement
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: spoke-argocd-crd

