apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: spoke-argocd-repos
  namespace: openshift-gitops
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/controls: ""
    policy.open-cluster-management.io/standards: ""
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: openshift-gitops
        spec:
          complianceType: musthave
          remediationAction: inform
          severity: critical
          subscription:
            name: openshift-gitops-operator
            namespace: openshift-gitops-operator
            channel: latest
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
          versions:
  remediationAction: enforce
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: spoke-required-operators-placement
  namespace: open-cluster-management-policies
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: NotIn
              values:
                - local-cluster
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: spoke-required-operators-placement
  namespace: open-cluster-management-policies
placementRef:
  name: spoke-required-operators-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: spoke-required-operators
    apiGroup: policy.open-cluster-management.io
    kind: Policy
