apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-nmstate
  namespace: openshift-gitops
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: management
  template:
    metadata:
      name: '{{ .name }}-nmstate'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: openshift-nmstate

      sources:
        - repoURL: https://charts.hknlab.io
          chart: nmstate
          targetRevision: 0.1.0
          helm:
            releaseName: nmstate
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/clusters/hub/values/nmstate.yaml

        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          # path: clusters/hub/extras/nmstate
          ref: values

      syncPolicy:
        automated:
          prune: false
        syncOptions:
        - CreateNamespace=true
