apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-cluster-configuration
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
        # selector:
        #   matchExpressions:
        #     - key: vendor
        #       operator: In
        #       values:
        #         - Openshift
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: '{{ .name }}-cluster-configuration'
    spec:
      project: '{{.name}}'

      destination:
        server: '{{ .server }}'
        namespace: openshift-config

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          # path: cluster/{{.name}}/extras/openshift-configuration
          ref: values

        - repoURL: https://charts.hknlab.io
          chart: openshift-configuration
          targetRevision: 0.1.1
          helm:
            releaseName: '{{ .name }}'
            ignoreMissingValueFiles: true
            valueFiles:
                - $values/environment/{{ .metadata.labels.environment }}/values/cluster-configuration.yaml
                - $values/cluster/{{ .name }}/values/cluster-configuration.yaml

      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - ServerSideApply=true
