apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-tdarr-server
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ .name }}-tdarr-server'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: arr-management

      sources:
        - repoURL: https://github.com/hyperkineticnerd/helm-charts.git
          path: charts/tdarr-server
          targetRevision: HEAD
          helm:
            releaseName: tdarr-server
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{.name}}/values/tdarr-server.yaml

        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: cluster/{{.name}}/extras/tdarr-server
          ref: values

      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
