apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 100-worker-blacklist-nouveau
spec:
  config:
    ignition:
      version: 3.5.0
  kernelArguments:
    - modprobe.blacklist=nouveau
