---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-storage-config
  namespace: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: vault-storage-config
  dataFrom:
    - extract:
        key: apps/vault/storage-config
