apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openvpn-external-secrets
  namespace: arr-downloaders
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: ClusterSecretStore  # or ClusterSecretStore
    name: vault-backend
  target:
    name: openvpn-secret
  data:
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: apps/gluetun/protonvpn/config
        property: provider

    - secretKey: VPN_TYPE
      remoteRef:
        key: apps/gluetun/protonvpn/config
        property: type

    - secretKey: VPN_PORT_FORWARDING
      remoteRef:
        key: apps/gluetun/protonvpn/config
        property: port_forwarding

    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: apps/gluetun/protonvpn/config
        property: private_key

    - secretKey: SERVER_COUNTRIES
      remoteRef:
        key: apps/gluetun/protonvpn/config
        property: server_countries

    # - secretKey: SERVER_HOSTNAMES
    #   remoteRef:
    #     key: apps/gluetun/protonvpn/config
    #     property: server_hostnames

    # - secretKey: OPENVPN_USER
    #   remoteRef:
    #     key: apps/gluetun/protonvpn/config
    #     property: username

    # - secretKey: OPENVPN_PASSWORD
    #   remoteRef:
    #     key: apps/gluetun/protonvpn/config
    #     property: password
