kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm-matrix-dendrite-signing-key-scc
  namespace: matrix-dendrite
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
subjects:
  - kind: ServiceAccount
    name: matrix-dendrite-signing-key
    namespace: matrix-dendrite
