apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-metube
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  template:
    metadata:
      name: '{{ .name }}-metube'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: metube

      sources:
        - repoURL: https://charts.hknlab.io
          chart: metube
          targetRevision: 0.1.0
          helm:
            releaseName: metube
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/clusters/{{.name}}/values/metube.yaml

        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: clusters/{{.name}}/extras/metube
          ref: values

      syncPolicy:
        automated:
          prune: false
        syncOptions:
        - CreateNamespace=true

      # ignoreDifferences:
      #   - group: Batch
      #     kind: Job
