apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-transmission
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ .name }}-transmission'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: arr-downloaders  # transmission

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: cluster/{{.name}}/extras/transmission
          ref: values

        - repoURL: oci://ghcr.io/lexfrei/charts/transmission
          path: .
          targetRevision: 1.8.0
          helm:
            releaseName: transmission
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{.name}}/values/transmission.yaml

      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
          - CreateNamespace=true
