apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-tdarr-node
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  template:
    metadata:
      name: '{{ .name }}-tdarr-node'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: arr-management

      sources:
        - repoURL: https://github.com/hyperkineticnerd/helm-charts.git
          path: charts/tdarr-node
          targetRevision: HEAD
          helm:
            releaseName: tdarr-node-1
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{.name}}/values/tdarr-node.yaml

        - repoURL: https://github.com/hyperkineticnerd/helm-charts.git
          path: charts/tdarr-node
          targetRevision: HEAD
          helm:
            releaseName: tdarr-node-2
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{.name}}/values/tdarr-node.yaml

        - repoURL: https://github.com/hyperkineticnerd/helm-charts.git
          path: charts/tdarr-node
          targetRevision: HEAD
          helm:
            releaseName: tdarr-node-3
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{.name}}/values/tdarr-node.yaml

        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: clusters/{{.name}}/extras/tdarr-node
          ref: values

      syncPolicy:
        automated:
          prune: false
        syncOptions:
        - CreateNamespace=true
