---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-secured-cluster-secret
  namespace: stackrox
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cluster-registration-secret
    template:
      engineVersion: v2
      metadata:
        annotations:
          crs.platform.stackrox.io/created-at: '{{ index . "created-at" }}'
          crs.platform.stackrox.io/expires-at: '{{ index . "expires-at" }}'
          crs.platform.stackrox.io/id: '{{ .id }}'
          crs.platform.stackrox.io/name: '{{ .name }}'
      data:
        crs: '{{ .crs }}'
  dataFrom:
    - extract:
        key: apps/stackrox/crs
