apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-external-secrets
  namespace: arr-collectors
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: radarr-config
  dataFrom:
    - extract:
        key: apps/radarr
