apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-rhacs-config
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - management
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ .name }}-rhacs-config'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: stackrox

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          # path: cluster/hub/extras/nmstate
          ref: values

        - repoURL: oci://ghcr.io/hyperkineticnerd/charts/rhacs-config
          # chart: rhacs-config
          path: .
          targetRevision: 0.8.6
          helm:
            releaseName: rhacs-config
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{ .name }}/values/rhacs-config.yaml

        - repoURL: oci://ghcr.io/hyperkineticnerd/charts/rhacs-config-central-declarative
          # chart: rhacs-config-central-declarative
          path: .
          targetRevision: 0.8.0
          helm:
            releaseName: rhacs-config-central-declarative
            ignoreMissingValueFiles: true
            valueFiles: []

        - repoURL: oci://ghcr.io/hyperkineticnerd/charts/rhacs-config-init-bundle
          # chart: rhacs-config-init-bundle
          path: .
          targetRevision: 0.1.1
          helm:
            releaseName: rhacs-config-init-bundle
            ignoreMissingValueFiles: true
            valueFiles: []

      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
