apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-rhacs-config
  namespace: openshift-gitops
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - management
  template:
    metadata:
      name: '{{ .name }}-rhacs-config'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: stackrox

      sources:
        - repoURL: https://charts.hknlab.io
          chart: rhacs-config
          targetRevision: 0.2.0
          helm:
            releaseName: rhacs-config
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/hub/values/rhacs-config.yaml

        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          # path: cluster/hub/extras/nmstate
          ref: values

      syncPolicy:
        automated:
          prune: false
        syncOptions:
        - CreateNamespace=true
