apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-jellyseerr
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  template:
    metadata:
      name: '{{ .name }}-jellyseerr'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: arr-management

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: cluster/{{.name}}/extras/jellyseerr
          ref: values

        - repoURL: oci://ghcr.io/seerr-team/seerr/seerr-chart
          path: .
          targetRevision: 3.3.0
          helm:
            releaseName: jellyseerr
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/{{.name}}/values/jellyseerr.yaml

      syncPolicy:
        automated:
          prune: false
        syncOptions:
        - CreateNamespace=true
