apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-compliance-operator
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        values:
          env: '{{index .metadata.labels "environment"}}'
          cluster: '{{ .name }}'
        # selector:
        #   matchExpressions:
        #     - key: environment
        #       operator: In
        #       values:
        #         - management
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.syncPolicy
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ .name }}-compliance-operator'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: openshift-compliance

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          # path: cluster/{{ .name }}/extras/nmstate
          ref: values

        - repoURL: oci://ghcr.io/hyperkineticnerd/charts/olm-operator
          # chart: olm-operator
          path: .
          targetRevision: 0.8.0
          helm:
            releaseName: compliance-operator
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/environment/all/values/compliance-operator.yaml
              - $values/environment/{{ .values.env }}/values/compliance-operator.yaml
              - $values/cluster/{{ .name }}/values/compliance-operator.yaml

      syncPolicy:
        automated:
          enabled: false
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true
