---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-hcp-sshkey-dev
  namespace: clusters
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: sshkey-cluster-dev
  data:
    - secretKey: id_rsa.pub
      remoteRef:
        key: cluster/dev/install/ssh
        property: public_key
