---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-dendrite-signing-key
  namespace: matrix-dendrite
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: my-dendrite-signing-key
  dataFrom:
    - extract:
        key: apps/matrix-dendrite/signing-key
        # property: .

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-dendrite-conf
  namespace: matrix-dendrite
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: matrix-dendrite-conf
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          argocd.argoproj.io/compare-options: IgnoreExtraneous
          argocd.argoproj.io/sync-options: Delete=false
  dataFrom:
    - extract:
        key: apps/matrix-dendrite/config
        # property: .
