apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-radarr
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: environment
              operator: In
              values:
                - production
  template:
    metadata:
      name: '{{ .name }}-radarr'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: arr-collectors

      sources:
        - repoURL: https://charts.hknlab.io
          chart: radarr
          targetRevision: 0.1.3
          helm:
            releaseName: radarr
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/clusters/{{.name}}/values/radarr.yaml

        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          path: clusters/{{.name}}/extras/radarr
          ref: values

      syncPolicy:
        automated:
          prune: false
        syncOptions:
        - CreateNamespace=true
