apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-metallb
  namespace: openshift-gitops
  annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            environment: management
  template:
    metadata:
      name: '{{ .name }}-metallb'
    spec:
      project: '{{ .name }}'

      destination:
        server: '{{ .server }}'
        namespace: metallb-system

      sources:
        - repoURL: https://gitlab.developer.hkn.lab/IaC/openshift4/clusters/all.git
          targetRevision: HEAD
          # path: cluster/{{.name}}/extras/metallb
          ref: values

        - repoURL: https://charts.hknlab.io
          chart: metallb-operator
          targetRevision: 0.1.0
          helm:
            releaseName: metallb

        - repoURL: https://charts.hknlab.io
          chart: metallb-bgp
          targetRevision: 0.1.5
          helm:
            releaseName: metallb
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/hub/values/bgp.yaml

        - repoURL: https://charts.hknlab.io
          chart: metallb-loadbalancer
          targetRevision: 0.1.1
          helm:
            releaseName: metallb
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/cluster/hub/values/lb.yaml

      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
          - SkipDryRunOnMissingResource=true
