---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-ingress-certs-dev
  namespace: openshift-ingress
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ingress-certs-dev
  data:
    - secretKey: tls.crt
      remoteRef:
        key: cluster/dev/certs/apps
        property: tls.crt
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: tls.key
      remoteRef:
        key: cluster/dev/certs/apps
        property: tls.key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
