kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: helm-metube-scc
  namespace: metube
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
subjects:
  - kind: ServiceAccount
    name: default
    namespace: metube
