apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-hcp-pullsecret-test2
  namespace: clusters
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: pullsecret-cluster-test2
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - extract:
        key: cluster/test2/install/pull-secret

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-hcp-sshkey-test2
  namespace: clusters
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: sshkey-cluster-test2
  data:
    - secretKey: id_rsa.pub
      remoteRef:
        key: cluster/test2/install/ssh
        property: public_key
